In [ ]:
pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.6)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [ ]:
"""
Consider following code to answer further questions:
import pandas as pd
course_name = [‘Data Science’, ‘Machine Learning’, ‘Big Data’, ‘Data Engineer’]
duration = [2,3,6,4]
df = pd.DataFrame(data = {‘course_name’ : course_name, ‘duration’ : duration})
"""

In [6]:
"""
Q1. Write a code to print the data present in the second row of the dataframe, df.
"""
import pandas as pd

course_name = ['Data Science', 'Machine Learning', 'Big Data', 'Data Engineer']

duration = [2,3,6,4]

df = pd.DataFrame(data = {'course_name' : course_name, 'duration' : duration})

print(df.loc[1])

course_name    Machine Learning
duration                      3
Name: 1, dtype: object

In [24]:
"""
Q2. What is the difference between the functions loc and iloc in pandas.DataFrame?
Ans.
"""
import pandas as pd

course_name = ['Data Science', 'Machine Learning', 'Big Data', 'Data Engineer']

duration = [2,3,6,4]

df = pd.DataFrame(data = {'course_name' : course_name, 'duration' : duration})

print(df.loc[1:2])
print(df.iloc[1])

        course_name  duration
1  Machine Learning         3
2          Big Data         6
course_name    Machine Learning
duration                      3
Name: 1, dtype: object

In [25]:
"""
Q3. Reindex the given dataframe using a variable, reindex = [3,0,1,2] and store it in the variable, new_df then find the output for
    both new_df.loc[2] and new_df.iloc[2].
    Did you observe any difference in both the outputs? If so then explain it.
Ans.
    Original DataFrame df:
       course_name  duration
0  Data Science         2
1  Machine Learning   3
2  Big Data          6
3  Data Engineer     4

    After Reindex :
   course_name  duration
3  Data Engineer     4
0  Data Science         2
1  Machine Learning   3
2  Big Data          6

The reindex list [3, 0, 1, 2] specifies the new order in which the rows should appear in the new_df. It effectively says that the row with
index 3 in the original DataFrame should become the first row, the row with index 0 should become the second row, and so on.

The df.reindex(reindex) method is called, which creates a new DataFrame new_df with the rows reordered based on the reindex

new_df.loc[2] will use label-based indexing (loc) to select the row with label 2. In this reordered DataFrame, the row with 
label 2 corresponds to 'Big Data' with a duration of 6. So, new_df.loc[2]

new_df.iloc[2] will use integer-based indexing (iloc) to select the row at position 2. In this reordered DataFrame, the row at position 
2 corresponds to 'Machine Learning' with a duration of 3.
"""
import pandas as pd

course_name = ['Data Science', 'Machine Learning', 'Big Data', 'Data Engineer']

duration = [2,3,6,4]
reindex = [3,0,1,2]

df = pd.DataFrame(data = {'course_name' : course_name, 'duration' : duration})

new_df = df.reindex(reindex)

print(new_df.loc[2])
print(new_df.iloc[2])

course_name    Big Data
duration              6
Name: 2, dtype: object
course_name    Machine Learning
duration                      3
Name: 1, dtype: object

In [ ]:
#Consider the below code to answer further questions:
import pandas as pd
import numpy as np
columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1,2,3,4,5,6]
#Creating a dataframe:
df1 = pd.DataFrame(np.random.rand(6,6), columns = columns, index = indices)

In [30]:
"""
Q4. Write a code to find the following statistical measurements for the above dataframe df1:
(i) mean of each and every column present in the dataframe.
(ii) standard deviation of column, ‘column_2’
"""
import pandas as pd
import numpy as np
columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1,2,3,4,5,6]
#Creating a dataframe:
df1 = pd.DataFrame(np.random.rand(6,6), columns = columns, index = indices)

column_means = df1.mean()
print("Mean of each column:")
print(column_means)


std_dev_column_2 = df1['column_2'].std()
print("\nStandard Deviation of 'column_2':", std_dev_column_2)

Mean of each column:
column_1    0.392530
column_2    0.353358
column_3    0.576261
column_4    0.614550
column_5    0.547989
column_6    0.512004
dtype: float64

Standard Deviation of 'column_2': 0.35410404102280035

In [40]:
"""
Q5. Replace the data present in the second row of column, ‘column_2’ by a string variable then find the
mean of column1, column_2.
If you are getting errors in executing it then explain why.
[Hint: To replace the data use df1.loc[] and equate this to string data of your choice.]
Ans. Yes there is an error on the frist time when i executed the program. the error was like ValueError or TypeError due to data type
     conflicts.
     to get rid of this i simply keep the data type consistency.
"""
import pandas as pd
import numpy as np
columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1,2,3,4,5,6]

df1 = pd.DataFrame(np.random.rand(6,6), columns = columns, index = indices)

df1.loc[2, 'column_2'] = 42.0 

# Calculate the mean of 'column_1' and 'column_2'
column1_mean = df1['column_1'].mean()
column2_mean = df1['column_2'].mean()

print("Mean of 'column_1':", column1_mean)
print("Mean of 'column_2':", column2_mean)

Mean of 'column_1': 0.5447858306980523
Mean of 'column_2': 7.383678590874918

In [36]:
df1

   column_1  column_2  column_3  column_4  column_5  column_6
1  0.317695  0.496381  0.342247  0.874166  0.734183  0.671126
2  0.878002      42.0  0.714966  0.429587  0.651930  0.710292
3  0.009221  0.837391  0.891387  0.645186  0.310876  0.483389
4  0.254762  0.046703  0.219866  0.520947  0.441235  0.158536
5  0.653627  0.025417  0.863041  0.937462  0.202584  0.134847
6  0.241875  0.649186  0.426061  0.279951  0.947127  0.913836

In [42]:
"""
Q6. What do you understand about the windows function in pandas and list the types of windows
    functions?
Ans.In pandas, a window function, also known as a rolling or moving window function, is a powerful tool for performing calculations on 
    a sliding window of data within a DataFrame or Series. It's particularly useful for time-series data or any data where you want to 
    analyze trends, moving averages, or other aggregations over a specific window or interval of data points.
    
    Window functions in pandas allow you to perform operations like:
    Rolling Mean: Calculating the mean of data points within a rolling window.
    Rolling Sum: Calculating the sum of data points within a rolling window.
    Rolling Standard Deviation: Calculating the standard deviation of data points within a rolling window.
    Rolling Min and Max: Finding the minimum and maximum values within a rolling window.
    Exponential Moving Average (EMA): Calculating the exponential moving average, which gives more weight to recent data points.
"""
import pandas as pd

data = {'value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)


rolling_window = df['value'].rolling(window=3)

print(rolling_window.mean())
print(rolling_window.sum())
print(rolling_window.std())
print(rolling_window.min())
print(rolling_window.max())

0     NaN
1     NaN
2    20.0
3    30.0
4    40.0
Name: value, dtype: float64
0      NaN
1      NaN
2     60.0
3     90.0
4    120.0
Name: value, dtype: float64
0     NaN
1     NaN
2    10.0
3    10.0
4    10.0
Name: value, dtype: float64
0     NaN
1     NaN
2    10.0
3    20.0
4    30.0
Name: value, dtype: float64
0     NaN
1     NaN
2    30.0
3    40.0
4    50.0
Name: value, dtype: float64

In [44]:
"""
Q7. Write a code to print only the current month and year at the time of answering this question.
[Hint: Use pandas.datetime function]
"""
import pandas as pd
from datetime import datetime

current_date = datetime.now()

current_month = current_date.month
current_year = current_date.year


df = pd.DataFrame({'Current Month': [current_month], 'Current Year': [current_year]})

print(df)

   Current Month  Current Year
0              9          2023

In [48]:
"""
Q8. Write a Python program that takes in two dates as input (in the format YYYY-MM-DD) and
calculates the difference between them in days, hours, and minutes using Pandas time delta. The
program should prompt the user to enter the dates and display the result.
"""
import pandas as pd

date_str1 = input("Enter the first date (YYYY-MM-DD): ")

date_str2 = input("Enter the second date (YYYY-MM-DD): ")

try:
    
    date1 = pd.to_datetime(date_str1)
    date2 = pd.to_datetime(date_str2)

    time_difference = date2 - date1

    days = time_difference.days
    seconds = time_difference.seconds
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)

    print(f"Time difference: {days} days, {hours} hours, {minutes} minutes")
except ValueError:
    print("Invalid date format. Please use the format 'YYYY-MM-DD'.")

Enter the first date (YYYY-MM-DD):  2023-10-10
Enter the second date (YYYY-MM-DD):  2023-12-15

Time difference: 66 days, 0 hours, 0 minutes

In [52]:
"""
Q9. Write a Python program that reads a CSV file containing categorical data and converts a specified column to a categorical data 
    type. The program should prompt the user to enter the file path, column name, and category order, and then display the sorted data.
"""
import pandas as pd

# Prompt the user to enter the file path
file_path = input("Enter the CSV file path: ")

# Prompt the user to enter the column name
column_name = input("Enter the column name to convert to categorical: ")

# Prompt the user to enter the custom category order as a comma-separated list
category_order = input("Enter the custom category order (comma-separated): ").split(',')

try:
    # Read the CSV file into a DataFrame
    df = pd.read_csv(file_path)

    # Convert the specified column to a categorical data type with custom categories
    df[column_name] = pd.Categorical(df[column_name], categories=category_order, ordered=True)

    # Sort the DataFrame by the specified column
    sorted_df = df.sort_values(by=column_name)

    # Display the sorted DataFrame
    print(sorted_df)
except FileNotFoundError:
    print("File not found. Please provide a valid file path.")
except KeyError:
    print(f"Column '{column_name}' not found in the CSV file.")

Enter the CSV file path:  services.csv
Enter the column name to convert to categorical:  program_id
Enter the custom category order (comma-separated):  2,1

    id  location_id program_id         accepted_payments  \
0    1            1        NaN                       NaN
1    2            2        NaN                       NaN
2    3            3        NaN                       NaN
3    4            4        NaN                       NaN
4    5            5        NaN                       NaN
5    6            6        NaN                       NaN
6    7            7        NaN                       NaN
7    8            8        NaN                       NaN
8    9            9        NaN                       NaN
9   10           10        NaN                       NaN
10  11           11        NaN                       NaN
11  12           12        NaN                       NaN
12  13           13        NaN                       NaN
13  14           14        NaN                       NaN
14  15           15        NaN                       NaN
15  16           16        NaN                       NaN
16  17           17        NaN                       NaN
17  18           18        NaN                       NaN
18  19           19        NaN                       NaN
19  20           20        NaN                       NaN
20  21           21        NaN                       NaN
21  22           22        NaN  Cash, Check, Credit Card
22  23           22        NaN                       NaN

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.
1                     NaN                 Apply by phone for an appointment.
2                     NaN        Phone for information (403-4300 Ext. 4322).
3                     NaN                                    Apply by phone.
4                     NaN                             Phone for information.
5                     NaN  Walk in or apply by phone for membership appli...
6                     NaN  Apply by phone or be referred by a doctor, soc...
7                     NaN                                    Apply by phone.
8                     NaN  Walk in. Proof of residency in California requ...
9                     NaN  Walk in. Proof of California residency to rece...
10                    NaN  Walk in. Proof of California residency require...
11                    NaN  Walk in or apply by phone, email or webpage re...
12                    NaN  Walk in. Proof of California residency require...
13                    NaN  Call for appointment. Referral from human serv...
14                    NaN          Walk in or through other agency referral.
15                    NaN  Walk in. Written application, identification r...
16                    NaN                              Call for information.
17                    NaN  Call for screening appointment. Medical visits...
18                    NaN     Call for screening appointment (650-347-3648).
19                    NaN                                           Walk in.
20                    NaN                    By phone during business hours.
21  Fotos para pasaportes                  Walk in or apply by phone or mail
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...
1        Residents of San Mateo County age 55 or over
2   Older adults age 55 or over who can benefit fr...
3   Parents, children, families with problems of c...
4   Low-income working families with children tran...
5                                             Any age
6   Older adults who have memory or sensory loss, ...
7   Senior citizens age 60 or over, disabled indiv...
8      Ethnic minorities, especially Spanish speaking
9                                                 NaN
10                                                NaN
11  Adults, parents, children in 1st-12th grades i...
12                                                NaN
13  Individuals or families with low or no income ...
14  Adult alcoholic/drug addictive men and women w...
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
0   A walk-in center for older adults that provide...
1   Provides training and job placement to eligibl...
2   Offers supportive counseling services to San M...
3   Provides supervised visitation services and a ...
4   Provides fixed 8% short term loans to eligible...
5   A multipurpose center offering a wide variety ...
6   Rosener House is a day center for older adults...
7   Delivers a hot meal to the home of persons age...
8   Provides general reading material, including b...
9   Provides general reading and media materials, ...
10  Provides general reading materials, including ...
11  Offers an intergenerational literacy program f...
12  Provides general reading materials, including ...
13  Provides food, clothing, bus tokens and shelte...
14  Provides a long-term (6-12 month) residential ...
15  Provides emergency assistance including food a...
16  Provides emergency food, clothing and furnitur...
17  By appointment only, Project Smile provides a ...
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                          eligibility                  email  \
0   Age 55 or over for most programs, age 60 or ov...                    NaN
1   Age 55 or over, county resident and willing an...                    NaN
2         Resident of San Mateo County age 55 or over                    NaN
3                                                None                    NaN
4   Eligibility: Low-income family with legal cust...                    NaN
5                                                None                    NaN
6                                      Age 18 or over                    NaN
7             Homebound person unable to cook or shop                    NaN
8     Resident of California to obtain a library card                    NaN
9             Resident of California to obtain a card                    NaN
10  Resident of California to obtain a library car...                    NaN
11  English-speaking adult reading at or below 7th...                    NaN
12    Resident of California to obtain a library card                    NaN
13  None for most services. For emergency assistan...                    NaN
14  Age 21-60, detoxed, physically able and willin...                    NaN
15                      None for emergency assistance                    NaN
16                                Low-income families                    NaN
17    Low-income person without access to health care                    NaN
18    Low-income person without access to health care                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                               None  passports@example.org
22                                               None                    NaN

    ...                            interpretation_services  \
0   ...                                                NaN
1   ...                                                NaN
2   ...                                                NaN
3   ...                                                NaN
4   ...                                                NaN
5   ...                                                NaN
6   ...                                                NaN
7   ...                                                NaN
8   ...                                                NaN
9   ...                                                NaN
10  ...                                                NaN
11  ...                                                NaN
12  ...                                                NaN
13  ...                                                NaN
14  ...                                                NaN
15  ...                                                NaN
16  ...                                                NaN
17  ...                                                NaN
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

                          required_documents  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  Government-issued picture identification
22                                       NaN

                            service_areas    status  \
0                                   Colma    active
1                        San Mateo County    active
2                        San Mateo County    active
3                        San Mateo County    active
4                        San Mateo County    active
5                        San Mateo County    active
6     Belmont, Burlingame, East Palo Alto    active
7                 Belmont, East Palo Alto    active
8                        San Mateo County    active
9                        San Mateo County    active
10                       San Mateo County    active
11                              Daly City    active
12                       San Mateo County    active
13    Belmont, Burlingame, East Palo Alto    active
14       Alameda County, San Mateo County    active
15                                    NaN    active
16  Colma, Daly City, South San Francisco    active
17                         East Palo Alto    active
18                    Belmont, Burlingame    active
19                                    NaN   defunct
20                       San Mateo County  inactive
21       Alameda County, San Mateo County    active
22       San Mateo County, Alameda County    active

                                            wait_time                 website  \
0                                            No wait.                     NaN
1                                             Varies.                     NaN
2                                             Varies.                     NaN
3                                            No wait.                     NaN
4                                                 NaN                     NaN
5                                            No wait.                     NaN
6                                            No wait.                     NaN
7                                            No wait.                     NaN
8                                            No wait.                     NaN
9                                            No wait.                     NaN
10                                           No wait.                     NaN
11  Depends on availability of tutors for small gr...                     NaN
12                                           No wait.                     NaN
13                                  Up to 20 minutes.                     NaN
14  Varies according to available beds for men and...                     NaN
15                                           No wait.                     NaN
16                                                NaN                     NaN
17                                            Varies.                     NaN
18                                            Varies.                     NaN
19                                                NaN                     NaN
20                                                NaN                     NaN
21                                No wait to 2 weeks.  http://www.example.com
22                                 No wait to 2 weeks  http://www.example.com

                                taxonomy_ids
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  105, 108, 108-05, 108-05-01, 111, 111-05
22                                       NaN

[23 rows x 22 columns]

In [ ]:
"""
Q10. Write a Python program that reads a CSV file containing sales data for different products and
visualizes the data using a stacked bar chart to show the sales of each product category over time. The
program should prompt the user to enter the file path and display the chart.
Ans. I dont know how to get a csv file. I checked on google but they give a large file with a very huge data
"""

In [ ]:
#same problem with question 11